// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: transcriber.proto

package transcriberv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Transcriber_Transcribe_FullMethodName = "/transcriber.v1.Transcriber/Transcribe"
)

// TranscriberClient is the client API for Transcriber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscriberClient interface {
	// Bidirectional streaming: client streams PCM chunks, server streams decoded segments as they are ready
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Segment], error)
}

type transcriberClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscriberClient(cc grpc.ClientConnInterface) TranscriberClient {
	return &transcriberClient{cc}
}

func (c *transcriberClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Segment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Transcriber_ServiceDesc.Streams[0], Transcriber_Transcribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscribeRequest, Segment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Transcriber_TranscribeClient = grpc.ServerStreamingClient[Segment]

// TranscriberServer is the server API for Transcriber service.
// All implementations must embed UnimplementedTranscriberServer
// for forward compatibility.
type TranscriberServer interface {
	// Bidirectional streaming: client streams PCM chunks, server streams decoded segments as they are ready
	Transcribe(*TranscribeRequest, grpc.ServerStreamingServer[Segment]) error
	mustEmbedUnimplementedTranscriberServer()
}

// UnimplementedTranscriberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscriberServer struct{}

func (UnimplementedTranscriberServer) Transcribe(*TranscribeRequest, grpc.ServerStreamingServer[Segment]) error {
	return status.Errorf(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedTranscriberServer) mustEmbedUnimplementedTranscriberServer() {}
func (UnimplementedTranscriberServer) testEmbeddedByValue()                     {}

// UnsafeTranscriberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscriberServer will
// result in compilation errors.
type UnsafeTranscriberServer interface {
	mustEmbedUnimplementedTranscriberServer()
}

func RegisterTranscriberServer(s grpc.ServiceRegistrar, srv TranscriberServer) {
	// If the following call pancis, it indicates UnimplementedTranscriberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Transcriber_ServiceDesc, srv)
}

func _Transcriber_Transcribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TranscriberServer).Transcribe(m, &grpc.GenericServerStream[TranscribeRequest, Segment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Transcriber_TranscribeServer = grpc.ServerStreamingServer[Segment]

// Transcriber_ServiceDesc is the grpc.ServiceDesc for Transcriber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transcriber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcriber.v1.Transcriber",
	HandlerType: (*TranscriberServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transcribe",
			Handler:       _Transcriber_Transcribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "transcriber.proto",
}
